In [1]:
import pandas as pd
import numpy as np

#Q1. Pandas version

In [2]:
pd.__version__

'2.2.2'

#Q2. Records count



#How many records are in the dataset?

In [3]:
data = pd.read_csv('laptops.csv')
data

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [63]:
record_count = len(data)
print(f'The record count is {record_count} rows.')

The record count is 2160 rows.


#Q3. Laptop brands



#How many laptop brands are presented in the dataset?

In [64]:
laptop_brands = data['Brand'].nunique()
print(f'The number of Laptop Brands are {laptop_brands} .')

The number of Laptop Brands are 27 .


#Q4. Missing values
    

#How many columns in the dataset have missing values?

In [65]:
missing_values = data.isnull().sum()
#missing_values = data[data.isnull().any()]
#missing_values = data[data].isnull().any()
missing_values

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

#Q5. Maximum final price


#What's the maximum final price of Dell notebooks in the dataset?

In [66]:
max_dell_price = data[data['Brand'] == 'Dell']['Final Price'].max()
#max_dell_price
print(f'Maximum Dell final price is ${max_dell_price}.')

Maximum Dell final price is $3936.0.


#Q6. Median value of Screen


#Find the median value of Screen column in the dataset.


#Next, calculate the most frequent value of the same Screen column.


#Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.


#Now, calculate the median value of Screen once again.

In [67]:
median_value = data['Screen'].median()
median_value

15.6

In [68]:
most_freq_value = data['Screen'].mode()
most_freq_value

0    15.6
Name: Screen, dtype: float64

In [69]:
data.Screen.fillna(15.6, inplace = True)
data['Screen']

/var/folders/9f/dspzp56j3pjcftph22hs9gw40000gn/T/ipykernel_69540/4124092461.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.Screen.fillna(15.6, inplace = True)


0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [70]:
n_median_value = data['Screen'].median()
n_median_value

15.6

#Q7. Sum of weights


#Select all the "Innjoo" laptops from the dataset.

#Select only columns RAM, Storage, Screen.

#Get the underlying NumPy array. Let's call it X.

#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

#Compute the inverse of XTX.

#Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

#What's the sum of all the elements of the result?

In [71]:
# 1. Select all the "Innjoo" laptops from the dataset.

innjoo = data[data['Brand'] == 'Innjoo']
innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [72]:
# 2. Select only columns RAM, Storage, Screen.

selected_col = data[['RAM','Storage','Screen']]
selected_col

RAM  Storage  Screen
0       8      512    15.6
1       8      256    15.6
2       8      256    15.6
3      16     1000    15.6
4      16      512    15.6
...   ...      ...     ...
2155   16     1000    17.3
2156   16     1000    17.3
2157   32     1000    17.3
2158   16     1000    13.4
2159   16      256    13.4

[2160 rows x 3 columns]

In [73]:
# 3. Get the underlying NumPy array. Let's call it X

X = data[['RAM','Storage','Screen']].to_numpy()
X

array([[   8. ,  512. ,   15.6],
       [   8. ,  256. ,   15.6],
       [   8. ,  256. ,   15.6],
       ...,
       [  32. , 1000. ,   17.3],
       [  16. , 1000. ,   13.4],
       [  16. ,  256. ,   13.4]])

In [74]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T @ X  # Alternatively, you can use np.dot(X.T, X)

print(XTX)


[[7.23420000e+05 2.56347520e+07 5.14286600e+05]
 [2.56347520e+07 1.04973173e+09 1.99103300e+07]
 [5.14286600e+05 1.99103300e+07 5.00128313e+05]]


In [75]:
# 5. Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 1.09915475e-05 -2.20639891e-07 -2.51893871e-06]
 [-2.20639891e-07  8.31868438e-09 -1.04284462e-07]
 [-2.51893871e-06 -1.04284462e-07  8.74134571e-06]]


In [76]:
# 6. Create the array y with the given values

y = np.array([1100, 1300, 800, 900, 1000, 1100])

print(y)

[1100 1300  800  900 1000 1100]


In [80]:
import numpy as np
import pandas as pd

# From DataFrame and select specific columns
df = pd.read_csv('laptops.csv')
#X = df[['RAM', 'Storage', 'Screen']].to_numpy()

# Ensure X has 6 rows to match y
X = df[['RAM', 'Storage', 'Screen']].to_numpy()[:6]

# Create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Step 1: Compute X.T @ X
XTX = X.T @ X

# Step 2: Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Step 3: Multiply the inverse of XTX by X.T
XTX_inv_XT = XTX_inv @ X.T

# Step 4: Multiply the result by y
w = XTX_inv_XT @ y

print(w)


[ 0.96091991 -0.1822925  70.96149855]


In [82]:
#What's the sum of all the elements of the result?

#Sum all elements of w

sum_w = np.sum(w)
sum_w

71.74012596026634